// Code generated by typesafe-gen. DO NOT EDIT.

package genexample

import typesafe "github.com/nibir1/typesafe-go"

// AllTopic lists every declared Topic, in declaration order.
var AllTopic = []Topic{
	TopicBilling,
	TopicTechnical,
	TopicSales,
	TopicOther,
}

// AllSeverity lists every declared Severity, in declaration order.
var AllSeverity = []Severity{
	SevNone,
	SevMinor,
	SevMajor,
	SevCritical,
}

// DepartmentQuestion is the "department" question: Which team should handle this ticket?
func (TicketQuestions) DepartmentQuestion() typesafe.TypedChoiceQuestion[Topic] {
	return typesafe.TypedChoice[Topic]("Which team should handle this ticket?",
		typesafe.OptionOf(TopicBilling, "Covers payments, invoicing and refunds."),
		typesafe.OptionOf(TopicTechnical, "Covers bugs, outages and integration failures."),
		typesafe.OptionOf(TopicSales, "Covers pricing, upgrades and new accounts."),
		typesafe.OptionOf(TopicOther, "Anything the other options do not cover."),
	)
}

// DepartmentAnswer decodes the "department" answer, checked against the declared option set.
func (q TicketQuestions) DepartmentAnswer(r *typesafe.SystemOneResponse) (typesafe.ChoiceAnswerOf[Topic], error) {
	return q.DepartmentQuestion().Answer(r, "department")
}

// SeverityQuestion is the "severity" question: How severe is the problem described here?
func (TicketQuestions) SeverityQuestion() typesafe.TypedScoreQuestion[Severity] {
	return typesafe.TypedScore[Severity]("How severe is the problem described here?",
		typesafe.LevelOf(SevNone, "No customer impact."),
		typesafe.LevelOf(SevMinor, "A degraded experience with a workaround."),
		typesafe.LevelOf(SevMajor, "A core feature is unusable."),
		typesafe.LevelOf(SevCritical, "The product is down or data is at risk."),
	)
}

// SeverityAnswer decodes the "severity" answer.
func (q TicketQuestions) SeverityAnswer(r *typesafe.SystemOneResponse) (typesafe.ScoreAnswerOf[Severity], error) {
	return q.SeverityQuestion().Answer(r, "severity")
}

// Questions returns every question declared by TicketQuestions.
//
// TicketQuestions is everything asked about one support ticket.
func (q TicketQuestions) Questions() typesafe.Questions {
	return typesafe.Questions{
		"department": q.DepartmentQuestion(),
		"severity":   q.SeverityQuestion(),
	}
}
