package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// writePkg puts src in a throwaway directory and returns its path.
func writePkg(t *testing.T, src string) string {
	t.Helper()
	dir := t.TempDir()
	if err := os.WriteFile(filepath.Join(dir, "x.go"), []byte(src), 0o644); err != nil {
		t.Fatalf("write: %v", err)
	}
	return dir
}

const choiceEnum = `package x

// Topic is the team that should handle a ticket.
type Topic string

const (
	// TopicBilling covers payments and refunds.
	TopicBilling Topic = "billing"

	// TopicTechnical covers bugs and outages.
	TopicTechnical Topic = "technical"
)

// Q asks about a ticket.
type Q struct {
	// Which team should handle this?
	Department Topic ` + "`typesafe:\"choice\"`" + `
}
`

func TestGeneratesAChoice(t *testing.T) {
	out, err := generate(writePkg(t, choiceEnum), "Q")
	if err != nil {
		t.Fatalf("generate: %v", err)
	}
	got := string(out)

	for _, want := range []string{
		"// Code generated by typesafe-gen. DO NOT EDIT.",
		"package x",
		"var AllTopic = []Topic{",
		"func (Q) DepartmentQuestion() typesafe.TypedChoiceQuestion[Topic]",
		`typesafe.TypedChoice[Topic]("Which team should handle this?"`,
		`typesafe.OptionOf(TopicBilling, "Covers payments and refunds.")`,
		"func (q Q) DepartmentAnswer(r *typesafe.SystemOneResponse) (typesafe.ChoiceAnswerOf[Topic], error)",
		`q.DepartmentQuestion().Answer(r, "department")`,
		"func (q Q) Questions() typesafe.Questions",
	} {
		if !strings.Contains(got, want) {
			t.Errorf("output is missing %q:\n%s", want, got)
		}
	}
}

// The doc comment convention puts the identifier first, which reads wrong as a
// description sent to a model.
func TestDescriptionsDropTheIdentifierPrefix(t *testing.T) {
	out, err := generate(writePkg(t, `package x

// Kind is a thing.
type Kind string

const (
	// KindAlpha is the first one.
	KindAlpha Kind = "alpha"

	// KindBeta means the second one.
	KindBeta Kind = "beta"

	// KindGamma covers everything else.
	KindGamma Kind = "gamma"

	KindDelta Kind = "delta"
)

// Q asks.
type Q struct {
	// Which kind?
	Kind Kind `+"`typesafe:\"choice\"`"+`
}
`), "Q")
	if err != nil {
		t.Fatalf("generate: %v", err)
	}
	got := string(out)

	for _, want := range []string{
		`typesafe.OptionOf(KindAlpha, "The first one.")`,
		`typesafe.OptionOf(KindBeta, "The second one.")`,
		`typesafe.OptionOf(KindGamma, "Covers everything else.")`,
		// No doc comment means a null description, which the API reads as
		// "interpret this option by its name alone".
		`typesafe.OptionOf(KindDelta, nil)`,
	} {
		if !strings.Contains(got, want) {
			t.Errorf("output is missing %q:\n%s", want, got)
		}
	}
}

func TestGeneratesAScore(t *testing.T) {
	out, err := generate(writePkg(t, `package x

// Sev is severity.
type Sev int

const (
	// SevNone is no impact.
	SevNone Sev = iota

	// SevSome is some impact.
	SevSome

	// SevBad is a lot of impact.
	SevBad
)

// Q asks.
type Q struct {
	// How bad is it?
	Impact Sev `+"`typesafe:\"score\"`"+`
}
`), "Q")
	if err != nil {
		t.Fatalf("generate: %v", err)
	}
	got := string(out)

	// Order is meaning for a Score, so the levels must be emitted lowest
	// first, in declaration order.
	iNone := strings.Index(got, "LevelOf(SevNone")
	iSome := strings.Index(got, "LevelOf(SevSome")
	iBad := strings.Index(got, "LevelOf(SevBad")
	if iNone < 0 || iSome < 0 || iBad < 0 {
		t.Fatalf("not all levels emitted:\n%s", got)
	}
	if !(iNone < iSome && iSome < iBad) {
		t.Errorf("levels are out of rubric order:\n%s", got)
	}
	if !strings.Contains(got, "typesafe.TypedScoreQuestion[Sev]") {
		t.Errorf("wrong question type:\n%s", got)
	}
}

// --- what the generator refuses ----------------------------------------------

func TestGeneratorErrors(t *testing.T) {
	cases := []struct {
		name string
		src  string
		typ  string
		want string
	}{
		{
			name: "a score enum declared out of order",
			// This is the mistake worth catching: every answer would map to
			// the wrong label and nothing in the score would reveal it.
			src: `package x

// Sev is severity.
type Sev int

const (
	// SevBad is bad.
	SevBad Sev = 2

	// SevNone is fine.
	SevNone Sev = 0
)

// Q asks.
type Q struct {
	// How bad?
	Impact Sev ` + "`typesafe:\"score\"`" + `
}
`,
			typ:  "Q",
			want: "position is its score",
		},
		{
			name: "a score enum with no determinable values",
			src: `package x

// Sev is severity.
type Sev int

// SevA is a.
const SevA Sev = 1 << 3

// Q asks.
type Q struct {
	// How bad?
	Impact Sev ` + "`typesafe:\"score\"`" + `
}
`,
			typ:  "Q",
			want: "integer literal",
		},
		{
			name: "a choice constant that is not a string",
			src: `package x

// Topic is a topic.
type Topic string

// TopicA is a.
const TopicA Topic = "a"

// Q asks.
type Q struct {
	// Which?
	Department Topic ` + "`typesafe:\"choice\"`" + `

	// Which other?
	Other Missing ` + "`typesafe:\"choice\"`" + `
}
`,
			typ:  "Q",
			want: "no constants of type Missing",
		},
		{
			name: "a field with no doc comment",
			src: `package x

// Topic is a topic.
type Topic string

// TopicA is a.
const TopicA Topic = "a"

// Q asks.
type Q struct {
	Department Topic ` + "`typesafe:\"choice\"`" + `
}
`,
			typ:  "Q",
			want: "no doc comment",
		},
		{
			name: "two fields sharing a question id",
			src: `package x

// Topic is a topic.
type Topic string

// TopicA is a.
const TopicA Topic = "a"

// Q asks.
type Q struct {
	// Which team?
	Department Topic ` + "`typesafe:\"choice\"`" + `

	// Which other team?
	Other Topic ` + "`typesafe:\"choice,id=department\"`" + `
}
`,
			typ:  "Q",
			want: "both use the question id",
		},
		{
			name: "a generated method colliding with a field",
			// Go forbids a method and a field with the same name, so this
			// would otherwise emit code that does not compile.
			src: `package x

// Topic is a topic.
type Topic string

// TopicA is a.
const TopicA Topic = "a"

// Q asks.
type Q struct {
	// Which team?
	Department Topic ` + "`typesafe:\"choice\"`" + `

	// DepartmentAnswer is a field that collides with the generated accessor.
	DepartmentAnswer string
}
`,
			typ:  "Q",
			want: "Go forbids a method and a field with the same name",
		},
		{
			name: "an unknown tag value",
			src: `package x

// Topic is a topic.
type Topic string

// Q asks.
type Q struct {
	// Which?
	Department Topic ` + "`typesafe:\"noul\"`" + `
}
`,
			typ:  "Q",
			want: `unknown typesafe tag "noul"`,
		},
		{
			name: "no tagged fields at all",
			src: `package x

// Q asks nothing.
type Q struct {
	Name string
}
`,
			typ:  "Q",
			want: "no fields tagged",
		},
		{
			name: "the type is not a struct",
			src: `package x

// Q is not a struct.
type Q string
`,
			typ:  "Q",
			want: "is not a struct type",
		},
		{
			name: "the type does not exist",
			src: `package x

// Q asks.
type Q struct{}
`,
			typ:  "Missing",
			want: "not found",
		},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			_, err := generate(writePkg(t, tc.src), tc.typ)
			if err == nil {
				t.Fatal("expected an error")
			}
			if !strings.Contains(err.Error(), tc.want) {
				t.Errorf("error = %q, want it to mention %q", err, tc.want)
			}
		})
	}
}

// --- id derivation -----------------------------------------------------------

func TestSnakeCase(t *testing.T) {
	cases := map[string]string{
		"Department":   "department",
		"IsUrgent":     "is_urgent",
		"APIKey":       "api_key",
		"HTTPStatus":   "http_status",
		"A":            "a",
		"CustomerTier": "customer_tier",
	}
	for in, want := range cases {
		if got := snakeCase(in); got != want {
			t.Errorf("snakeCase(%q) = %q, want %q", in, got, want)
		}
	}
}

func TestExplicitIDOverridesTheFieldName(t *testing.T) {
	out, err := generate(writePkg(t, `package x

// Topic is a topic.
type Topic string

// TopicA is a.
const TopicA Topic = "a"

// Q asks.
type Q struct {
	// Which team?
	Department Topic `+"`typesafe:\"choice,id=team\"`"+`
}
`), "Q")
	if err != nil {
		t.Fatalf("generate: %v", err)
	}
	if !strings.Contains(string(out), `"team": q.DepartmentQuestion()`) {
		t.Errorf("the explicit id was not used:\n%s", out)
	}
}

// Regenerating must be a no-op: the generator skips its own previous output,
// so running it twice cannot compound.
func TestRegenerationIsStable(t *testing.T) {
	dir := writePkg(t, choiceEnum)

	first, err := generate(dir, "Q")
	if err != nil {
		t.Fatalf("generate: %v", err)
	}
	if err := os.WriteFile(filepath.Join(dir, "q_typesafe.go"), first, 0o644); err != nil {
		t.Fatalf("write: %v", err)
	}

	second, err := generate(dir, "Q")
	if err != nil {
		t.Fatalf("regenerate: %v", err)
	}
	if string(first) != string(second) {
		t.Errorf("regeneration changed the output:\n--- first ---\n%s\n--- second ---\n%s",
			first, second)
	}
}
